<link rel="stylesheet" href="/css/style.css" type="text/css">
<link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<#--<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>-->
<#--<script src="https://cdn.jsdelivr.net/npm/vue-resource@1.5.1"></script>-->
<#--<script>-->
    <#--let frontData = [[${frontData}]]-->
<#--</script>-->